SESSION_KEY_PREFIX = 'key:'
SESSION_TYPE = 'file'
SECRET_KEY = 'some super secret key!'
SESSION_COOKIE_SECURE = True
SESSION_COOKIE_HTTPONLY = True
SESSION_PERMANENT = True
PERMANENT_SESSION_LIFETIME = 60 * 60 * 10
JSON_AS_ASCII = False
